In [1]:
import os
os.sys.path

['C:\\Users\\esteb\\Downloads',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\lib',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39',
 '',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\win32',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\esteb\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\Pythonwin']

In [2]:
import cv2
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [3]:
train_data_dir = 'C:/Users/esteb/Downloads/CarneDataset/train'

In [4]:
test_data_dir = 'C:/Users/esteb/Downloads/CarneDataset/test'

In [5]:
class_names = ['CLASS_01', 'CLASS_02', 'CLASS_03', 'CLASS_04', 'CLASS_05', 'CLASS_06', 'CLASS_07', 'CLASS_08']

In [6]:
def load_train_data(train_data_dir, class_names):
    images = []
    labels = []
    for class_index, class_name in enumerate(class_names):
        class_dir = os.path.join(train_data_dir, class_name)
        for img_file in os.listdir(class_dir):
            img = cv2.imread(os.path.join(class_dir, img_file))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            img = cv2.resize(img, (200, 200)) 
            images.append(img)
            labels.append(class_index)
    return np.array(images), np.array(labels)

def load_test_data(test_data_dir, class_names):
    images = []
    labels = []
    for class_index, class_name in enumerate(class_names):
        class_dir = os.path.join(test_data_dir, class_name)
        for img_file in os.listdir(class_dir):
            img = cv2.imread(os.path.join(class_dir, img_file))
            img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convertir a escala de grises si es necesario
            img = cv2.resize(img, (200, 200)) 
            images.append(img)
            labels.append(class_index)
    return np.array(images), np.array(labels)

In [7]:
train_images, train_labels = load_train_data(train_data_dir, class_names)

In [8]:
test_images, test_labels = load_test_data(train_data_dir, class_names)

In [9]:
train_images_flat = train_images.reshape(train_images.shape[0], -1)

In [10]:
test_images_flat = test_images.reshape(test_images.shape[0], -1)

In [11]:
classifier = SVC()

In [12]:
classifier.fit(train_images_flat, train_labels)

SVC()

In [13]:
predictions = classifier.predict(test_images_flat)

In [14]:
accuracy = accuracy_score(test_labels, predictions)

In [15]:
print("Precisión del clasificador: {:.2f}%".format(accuracy*100))

Precisión del clasificador: 95.59%


In [16]:
confusion_mat = confusion_matrix(test_labels, predictions)

In [17]:
print("Matriz de Confusión de entrenamiento:")
print(confusion_mat)

Matriz de Confusión de entrenamiento:
[[ 34  11   0  15   0   2   0]
 [  0 206   1   4   0   2   0]
 [  0   1 103   0   0   1   0]
 [  0   1   0 947   0   1   0]
 [  0   0   0   1  36   0   0]
 [  0   1   0   0   0 203   0]
 [  0   0   0  31   0   0  32]]
